$:
  vscode:
    - runner:
        cpus: 64
      docker:
        build: .ide/Dockerfile
        image: node:latest
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
        - name: npm
          script: npm list