# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 64
      services:
        - vscode
        - docker
      docker:
        image: docker.cnb.cool/xmzzuzhi/cnb-docker/node:latest
      env:
        - ANTHROPIC_BASE_URL=https://ai.gitee.com/anthropic
        - ANTHROPIC_AUTH_TOKEN
        - ANTHROPIC_MODEL=kimi-k2-instruct
        - ANTHROPIC_SMALL_FAST_MODEL=kimi-k2-instruct
      imports:
        - https://cnb.cool/XMZZUZHI/key/-/blob/main/CLI.yml
      stages:
        - name: 更换NPM源
          script:
            npm config set registry https://repo.huaweicloud.com/repository/npm/
        - name: 赋予GPG脚本权限
          script:
            chmod +x /workspace/install_gpg_keys.sh
        - name: 安装 iFlow CLI
          script:
            npm i -g @iflow-ai/iflow-cli@latest
        - name: 安装 Codebuddy Code CLI
          script:
            npm install -g @tencent-ai/codebuddy-code 
        - name: 安装 Claude Code
          script:
            npm install -g @anthropic-ai/claude-code