# Hexo 配置
## 文档: https://hexo.io/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/

# 站点配置
title: MZwiki
subtitle: '百科'
description: 'WZ百科是一个  百科网站,专注于分享知识和信息。'
keywords: '百科,知识,wiki'
author: 祁潇潇
language:
  - zh-CN
  - en
  - ja
  - ko
  - fr
  - de
  - es
  - ru
timezone: Asia/Shanghai

# URL 配置
## 在此设置您的站点 URL。例如，如果您使用 GitHub Page，请将 URL 设置为 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # 设置为 false 以移除永久链接中的 'index.html'
  trailing_html: true # 设置为 false 以移除永久链接中的 '.html'

# 目录配置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作配置
new_post_name: :title.md # 新文章的文件名
default_layout: post
titlecase: false # 将标题转换为标题格式
external_link:
  enable: true # 在新标签页中打开外部链接
  field: site # 应用于整个站点
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true # 显示行号
  auto_detect: false # 自动检测语言
  tab_replace: '' # 替换制表符
  wrap: true # 换行
  hljs: false
prismjs:
  preprocess: true # 预处理
  line_number: true # 显示行号
  tab_replace: '' # 替换制表符

# 首页配置
# path: 博客索引页的根路径（默认为空）
# per_page: 每页显示的文章数（0 表示禁用分页）
# order_by: 文章排序（默认按日期降序排列）
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类与标签配置
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## 参考: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
## Hexo 使用 Moment.js 解析和显示日期
## 您可以自定义日期格式，参考:
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option 支持 'mtime', 'date', 'empty'
updated_option: 'mtime'

# 分页配置
## 将 per_page 设置为 0 以禁用分页
per_page: 10
pagination_dir: page

# # 包含/排除文件
# ## include:/exclude: 选项仅适用于 'source/' 文件夹
# include:
# exclude:
# ignore:

# 扩展配置
## 插件: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/
theme: stellar

# 部署配置
## 文档: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
