article:
  type: tech
  # 使用之前请先通过npm i hexo-related-popular-posts安装
  related_posts:
  enable: true
  title: 您可能感兴趣的文章
  share:  [wechat, weibo, email, link]
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: friends
      theme: ''
      title: 友情链接
      icon: ''
      url: /friends/
style:
  leftbar:
    background-image: url(https://api.pearktrue.cn/api/beautifulgirl?type=image)
search:
  service: local_search # local_search, todo...
  local_search:
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    skip_search: [*.css,*.js] # 指定 path 中的内容不被搜索。
    codeblock: true # 是否搜索代码块（需要content: true)
footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder/social/08a41b181ce68.svg"/>'
      url: https://github.com/xiaomizhoubaobei
tag_plugins:
  emoji:
  # 表情速查表 https://weekdaycare.cn/posts/emoji-blob/
    default: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/qq/{name}.gif
    twemoji: https://gcore.jsdelivr.net/gh/twitter/twemoji/assets/svg/{name}.svg
    qq: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/qq/{name}.gif
    aru: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/aru-l/{name}.gif
    tieba: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/tieba/{name}.png
  image:
    fancybox: false
data_services:
  # {% link %}
  siteinfo:
    # 设置 api 可以自动提取网页标题、图标，服务部署方法：https://github.com/xaoxuu/site-info-api/
    # 接口测试通过后，把按钮的 href 部分替换成 {href} 之后填写到下方，例如：https://api.xaox.cc/site_info/v1?url={href}
    api: https://api.xaox.cc/site_info/v1?url={href}