name: Badgetizr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Badgetizr
        uses: badgetizr/badgetizr-action@v1
        with:
          github-token: ${{ secrets.TOKEN }}