name: 提交检查

on:
  push:
  pull_request:
    branches: 'main'

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions:  # 使用权限是因为需要使用PR评论功能
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # 检出PR HEAD提交
          fetch-depth: 0  # 合并基础检查所需
      - uses: commit-check/commit-check-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # 使用GITHUB-TOKEN是因为需要使用PR评论功能
        with:
          message: true
          branch: true
          author-name: true
          author-email: true
          commit-signoff: true
          merge-base: false
          imperative: false
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}